### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by PanagiotisTheof** [rmcgirr83/pmwelcome#4]
@rmcgirr83  just installed it on phpbb 3.3.7, PHP 7.3.10
I get this error when I try to preview or save the pm:

```
General Error
SQL ERROR [ mysqli ]

Incorrect string value: '\xF0\x9F\x93\xB8 ...' for column 'config_value' at row 1 [1366]

SQL

UPDATE phpbb_config_text SET config_value = 'test' WHERE config_name = 'pmwelcome_post_text'

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 1020
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 202
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 345
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/phpbb/config/db_text.php
LINE: 103
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/ext/apwa/pmwelcome/controller/admin_controller.php
LINE: 178
CALL: phpbb\config\db_text->set_array()

FILE: [ROOT]/ext/apwa/pmwelcome/acp/pmwelcome_module.php
LINE: 36
CALL: apwa\pmwelcome\controller\admin_controller->display_options()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: apwa\pmwelcome\acp\pmwelcome_module->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()
```

**Comment by rmcgirr83** [comment]
That's a collation error on the config_value column in the database.  What are you trying to input into the settings of the extension?

**Comment by PanagiotisTheof** [comment]
I was sending a quite long PM, with several bbcodes in it:

```
[align=center][size=130][b]Welcome to Paparizou Forum
Helena's Official International Fan Club![/b][/size][/align]


We're thrilled to have you join our vibrant community dedicated to Helena, the iconic Greek pop-star we all adore! [b]Your journey with us is bound to be unforgettable![/b] 


[size=110][b]✨ A global fan community! ✨[/b][/size]
Since our inception in 2006, Paparizou Forum has been uniting Helena's fans from around the world for 17 years! Originally known as PaparizouPlaceForum, [b]Helena herself gave us the name Paparizou Forum, which we adopted in 2009.[/b] Today, we stand tall with pride, boasting an impressive community of 1400 members and a vast media collection with ultra rare photos & videos from 1999 to today!

[b][url=https://www.youtube.com/watch?v=sF3fmHERTKA]In 2015, Helena herself recognized us as her Official International Fan Club[/url][/b] (click to watch), and we continue to thrive as an independent, creative, and inclusive community.



[align=center][size=130][b]Ready to dance the [i]Mambo[/i]?[/b] 
[b][i][url=https://www.youtube.com/watch?v=-W4ctfpB6Sc]Το χεις ή δεν το χεις? Στην δράση θέλω να σε δω...![/url][/i][/b][/size]
[i]:en: Do you have what it takes? I want to see you in action...![/i][/align]



[color=#CB536F][b][size=110]📸   Unlock Rare & Exclusive Media - You are only 10 posts away![/size][/b][/color]
[b]Make your first 10 posts[/b] to gain access to our vast collection of rare and exclusive [url=http://paparizouforum.com/boards/viewforum.php?f=147]photos[/url] & [url=http://paparizouforum.com/boards/viewforum.php?f=146]videos[/url], spanning Helena's journey since 1999! [b]Here are some ideas on how to participate and up your post count:[/b]

[color=#CB536F][b][size=110]👑   Post your Way to the Crown![/size][/b][/color]
Each post brings you closer to becoming the [b]King of Elenada[/b]! Stay active in our community by replying in topics and climb the member ranks of Paparizou Forum. [url=http://paparizouforum.com/boards/viewtopic.php?t=357]Learn More about the ranks[/url]

[color=#CB536F][b][size=110]🎤   Introduce Yourself:[/size][/b][/color]
Head over to [url=http://paparizouforum.com/boards/viewforum.php?f=131]Welcome![/url] section and create a topic to introduce yourself to our welcoming community! We can't wait to hear your story!

[color=#CB536F][b][size=110]💬   Your Opinion Matters:[/size][/b][/color]
We value your voice! Head over to [url=http://paparizouforum.com/boards/viewforum.php?f=131]Polls & Opinions[/url] , pick a topic that matters to you (on Helena's career, discography and more), and exchange your opinions with the rest members!

[color=#CB536F][b][size=110]💼   Create your Paparicious "Office":[/size][/b][/color]
Did you see something that caught your attention, and want to share with other members? Need to keep a diary somewhere? Need to write your groceries list, just so you don't forget it? Your [url=http://paparizouforum.com/boards/viewforum.php?f=133]Paparicious Office[/url] is the place to do so, and all the members are here to "spy" on you, and have fun altogether! Simply create a topic with your username as the title.

[color=#CB536F][b][size=110]💡 Read the Forum Policy & Guidelines: [/size][/b][/color]
To ensure our community remains respectful and enjoyable for everyone, we kindly request that you read the forum Policy & Guidelines.


[align=center][size=130][b][i]Let's Open a [url=https://www.youtube.com/watch?v=rX4M6zb35_M]Door to Heaven![/url][/i]  
[i][url=https://www.youtube.com/watch?v=-DNoZ7RWiIQ]Φυσικά Μαζί![/i][/url][/b] [/size]

 :papa:
```

**Comment by rmcgirr83** [comment]
It has something to do with the non English letters you're using. The
collation on your config text table is incorrect. What is the collation of
the config_value field. That is a default table of phpBB and not something
that is created by this extension.

**Comment by PanagiotisTheof** [comment]
Ok, I did several tests and it's clear now. It can process the Greek characters, but **it cannot process the emojis.**
That's not happening anywhere else in the forum. Emojis work just fine. 

Collation of phpbb_config_text is: utf8_bin if that's what you are asking....
(I am sorry, I am not really familiar with databases. If that's not what you need, I would appreciate it if you could guide me in phpmyadmin)

**Comment by rmcgirr83** [comment]
I'm pretty sure that column needs to be utf8_unicode_ci for emojis BUT that
isn't the way the default phpBB handles that. You'd probably be best served
by opening a support topic at phpBB and seeing if any repercussions would
happen if the collation was changed on that column in the db. That table is
used quite a bit in phpBB like with the contact page if I recall correctly.

**Comment by PanagiotisTheof** [comment]
Thanks a lot for your help! Much appreciated.

Still, I am wondering why emojis display normally in topic titles and posts without a problem. I 've checked all my tables, and the collation is utf8_bin for all of them... Anyway...

**Comment by rmcgirr83** [comment]
Pretty sure if you look at topic_text for posts it won't be as you state

**Comment by rmcgirr83** [comment]
Changing the collation on my test forum had zero effect. Let me mess around with it and I'll get back to you.

**Comment by PanagiotisTheof** [comment]
Thanks a lot! I have already asked in the phpbb support forums, but got no answer yet…Sent from my iPhoneOn 27 Jul 2023, at 3:54 PM, Rich McGirr ***@***.***> wrote:﻿
Changing the collation on my test forum had zero effect. Let me mess around with it and I'll get back to you.

**Comment by rmcgirr83** [comment]
This commit should fix it
https://github.com/rmcgirr83/pmwelcome/commit/0d4447a1bdabda86eb61fc088b57d93c0687aaf0

**Comment by PanagiotisTheof** [comment]
> This commit should fix it [0d4447a](https://github.com/rmcgirr83/pmwelcome/commit/0d4447a1bdabda86eb61fc088b57d93c0687aaf0)

Thanks a lot! So, should I still change the column collation?
In order to use the commit, should I just edit or replace the affected files? (composer.json & admin_controller.php)

**Comment by rmcgirr83** [comment]
No need to change the collation and you can just replace the files.
Remember to disable the extension first before writing over the files.

**Comment by PanagiotisTheof** [comment]
Thanks, I just tried it. It fixed the PM text, but not the PM Title. That's enough for me, but maybe you want to look into it for a future release. Thanks again!

**Comment by rmcgirr83** [comment]
Everything, including emojis in subject line, has been fixed in this commit. https://github.com/rmcgirr83/pmwelcome/commit/8f7288decea42d9fe2351ed5fc4ee2baedec3163

**Comment by PanagiotisTheof** [comment]
Thanks a lot! This fixed everything!
